<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Jhansi29" failures="0" tests="8" name="com.test.qa.tests.GroupDependency_testNG_ex_02" time="0.098" errors="1" timestamp="2025-03-20T20:01:18 IST" skipped="4">
  <testcase classname="com.test.qa.tests.GroupDependency_testNG_ex_02" name="Test4" time="0.000">
    <skipped/>
  </testcase> <!-- Test4 -->
  <system-out/>
  <testcase classname="com.test.qa.tests.GroupDependency_testNG_ex_02" name="Test7" time="0.007"/>
  <system-out/>
  <testcase classname="com.test.qa.tests.GroupDependency_testNG_ex_02" name="Test3" time="0.000">
    <skipped/>
  </testcase> <!-- Test3 -->
  <system-out/>
  <testcase classname="com.test.qa.tests.GroupDependency_testNG_ex_02" name="Test1" time="0.080">
    <error message="/ by zero" type="java.lang.ArithmeticException">
      <![CDATA[java.lang.ArithmeticException: / by zero
at com.test.qa.tests.GroupDependency_testNG_ex_02.Test1(GroupDependency_testNG_ex_02.java:10)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- Test1 -->
  <system-out/>
  <testcase classname="com.test.qa.tests.GroupDependency_testNG_ex_02" name="Test2" time="0.006"/>
  <system-out/>
  <testcase classname="com.test.qa.tests.GroupDependency_testNG_ex_02" name="Test5" time="0.005"/>
  <system-out/>
  <testcase classname="com.test.qa.tests.GroupDependency_testNG_ex_02" name="Test0" time="0.000">
    <skipped/>
  </testcase> <!-- Test0 -->
  <system-out/>
  <testcase classname="com.test.qa.tests.GroupDependency_testNG_ex_02" name="Test6" time="0.000">
    <skipped/>
  </testcase> <!-- Test6 -->
  <system-out/>
</testsuite> <!-- com.test.qa.tests.GroupDependency_testNG_ex_02 -->
